kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: pure-file-delay-binding
  labels:
    kubernetes.io/cluster-service: "true"
    chart: pure-csi
    release: "pure-storage-driver"
allowVolumeExpansion: true 
provisioner: pure-csi 
volumeBindingMode: WaitForFirstConsumer
parameters: 
   backend: file