apiVersion: snapshot.storage.k8s.io/v1alpha1
kind: VolumeSnapshot
metadata:
  name: volumesnapshot-1-test
spec:
  snapshotClassName: pure-snapshotclass
  source:
    name: datadir-cockroachdb-0
    kind: PersistentVolumeClaim