kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: cns-vvols
  annotations:
    storageclass.kubernetes.io/is-default-class: \"false\"
provisioner: csi.vsphere.vmware.com
parameters:
  storagepolicyname: "pure-vvols"
  fstype: ext4
